### ISSUE TITLE
Threading expressions helpers using ->>

### ISSUE THREAD

**Issue by budu** [pallet/thread-expr#1]
What do you think about some macro to help with `->>`, like this version of `when->>`:

```
(defmacro when->>
  [condition & body]
  (let [arg (last body)
        body (butlast body)]
    `(let [arg# ~arg]
       (if ~condition
         (->> arg# ~@body)
         arg#))))
```

**Comment by sritchie** [comment]
budu, sorry about the delay, here -- I took some time tonight and implemented `->>` versions of every macro in the library, along with tests. It's [in this feature branch](https://github.com/pallet/thread-expr/tree/feature/last-threader) until I can take a closer look in the AM, to make sure all is bug free! Please let me know if this helps, or if you have any feedback.

**Comment by budu** [comment]
That's great, I wasn't even asking for that much! Thanks

P.S.: I might try myself at some refactoring later on, I had an idea about a macro that would be great to define these.

**Comment by sritchie** [comment]
Great, looking forward to seeing it. There are definitely a few
patterns lurking :) I think it might be fun to implement -?> and -?>>
helpers, as the next addition.

On Monday, May 9, 2011, budu
reply@reply.github.com
wrote:

**Comment by budu** [comment]
Those could be copied from contrib.core, you should probably created a new issue for them tough.

**Comment by budu** [comment]
> P.S.: I might try myself at some refactoring later on, I had an idea about a macro that would be great to define these.

I've done it, but it needed more black magic than I had thought at first. I've posted an example of the code to clojure-dev here: https://groups.google.com/forum/#!topic/clojure-dev/nIOqgCmuBmY

I'll be waiting for answers to see if there's an easier way before completing the refactoring. Also I wonder if you or Hugo find that it's a good idea or if it's too evil for this library?

**Comment by hugoduncan** [comment]
I believe these are now in thread-expr
