### ISSUE TITLE
More general threading operator

### ISSUE THREAD

**Issue by AndreasKostler** [pallet/thread-expr#3]
Hi,
what do you think of the following:

``` clojure
(defmacro -x>
        ([x] x)
        ([x form] (if (seq? form)
                      (with-meta (replace {'_ x} form) (meta form))
                      (list form x)))
        ([x form & more] `(test-> (test-> ~x ~form) ~@more)))
```

Which allows inserting x into arbitrary positions:

``` clojure
(-x> "foo"
  (wrap-something "bar" _ "baz")
  println)
```

**Comment by hugoduncan** [comment]
I think it is outside the scope of this library to add new fundamental threading macros. I think the aim is just provide macros to help using clojure's built in threading macros.

That said, if this gets added to some other lib, we could consider adding support for it here.
